stages:
  prepare_data:
    cmd: python src/applications/prepare_data.py 
    deps:
      - src/applications/prepare_data.py
      - src/ml/data_processor.py
      - src/data_layer/data_connector.py
      - data/raw/Hypertension_Data_Set.csv
    params:
      - prepare.test_size
      - prepare.val_size
      - prepare.random_state
    outs:
      - data/processed/train.csv
      - data/processed/val.csv
      - data/processed/test.csv
    metrics:
      - reports/data_metrics.json:
          cache: false

  validate_data:
    cmd: python src/applications/validate_data.py
    deps:
      - src/applications/validate_data.py
      - data/processed/train.csv
      - data/processed/val.csv
      - data/processed/test.csv
    outs:
      - data/processed/train_clean.csv
      - data/processed/val_clean.csv
      - data/processed/test_clean.csv
    metrics:
      - reports/data_validation_report.json

  train_model:
    cmd: python src/applications/training.py --train-only
    deps:
      - src/applications/training.py
      - src/ml/training_pipeline.py
      - src/ml/data_processor.py
      - src/ml/cross_validator.py
      - src/ml/model.py
      - data/processed/train_clean.csv
      - data/processed/val_clean.csv
    params:
      - model.model_type
      - model.random_state
      - model.random_forest.n_estimators
      - model.random_forest.max_depth
      - model.logistic_regression.C
      - model.logistic_regression.max_iter
    outs:
      - models_chpt/hypertension_model.pkl
    metrics:
      - reports/training_metrics.json:
          cache: false

