name: bp-monitoring-env
channels:
  - defaults
dependencies:
  - pip
  - pip:
    - streamlit
    - requests
    - pandas
    - numpy
    - plotly
    - scikit-learn
    - python-multipart
    - pyyaml
    - dotenv

