name: bp-monitoring-env
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.6.0
  - appnope=0.1.4
  - asttokens=3.0.0
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - cairo=1.16.0
  - comm=0.2.1
  - dav1d=1.2.1
  - debugpy=1.8.11
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.7.1
  - fontconfig=2.14.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gettext=0.21.0
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - joblib=1.5.2
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - lcms2=2.16
  - lerc=4.0.0
  - libavif=1.1.1
  - libcxx=19.1.7
  - libdeflate=1.22
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran-ng=3.0.1
  - libgfortran5=11.3.0
  - libglib=2.84.2
  - libiconv=1.16
  - libmpdec=4.0.0
  - libopenblas=0.3.29
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.7.0
  - libwebp-base=1.3.2
  - libxgboost=3.0.5
  - libxml2=2.13.8
  - llvm-openmp=19.1.7
  - lz4-c=1.9.4
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.6
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numexpr=2.11.0
  - numpy-base=2.3.1
  - openblas=0.3.1
  - openjpeg=2.5.2
  - openssl=3.5.4
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - prompt_toolkit=3.0.43
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-xgboost=3.0.5
  - python=3.13.5
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - pyzmq=26.2.0
  - readline=8.3
  - scikit-learn=1.7.2
  - seaborn=0.13.2
  - setuptools=72.1.0
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.2.0
  - threadpoolctl=3.6.0
  - tk=8.6.15
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - aiobotocore==2.25.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.0
      - aiohttp-retry==2.9.1
      - aioitertools==0.12.0
      - aiosignal==1.4.0
      - alembic==1.17.0
      - amqp==5.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - appdirs==1.4.4
      - asyncssh==2.21.1
      - atpublic==6.0.2
      - authlib==1.6.5
      - awscli==1.42.50
      - backoff==2.2.1
      - billiard==4.2.2
      - boto3==1.40.49
      - botocore==1.40.49
      - cachetools==6.2.0
      - celery==5.5.3
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - click==8.3.0
      - click-didyoumean==0.3.1
      - click-plugins==1.1.1.2
      - click-repl==0.3.0
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - configobj==5.0.9
      - contourpy==1.3.3
      - cryptography==43.0.3
      - cycler==0.12.1
      - cyclopts==3.24.0
      - dacite==1.6.0
      - dagshub==0.6.3
      - dagshub-annotation-converter==0.1.13
      - databricks-sdk==0.67.0
      - dataclasses-json==0.6.7
      - dictdiffer==0.9.0
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.8.0
      - docker==7.1.0
      - docstring-parser==0.17.0
      - docutils==0.19
      - dpath==2.2.0
      - dulwich==0.24.2
      - dvc==3.63.0
      - dvc-data==3.16.12
      - dvc-gdrive==3.0.1
      - dvc-http==2.32.0
      - dvc-objects==5.1.2
      - dvc-render==1.0.2
      - dvc-s3==3.2.2
      - dvc-studio-client==0.22.0
      - dvc-task==0.40.2
      - email-validator==2.3.0
      - entrypoints==0.4
      - fastapi==0.119.1
      - fastapi-cli==0.0.14
      - fastapi-cloud-cli==0.3.1
      - fastmcp==2.12.4
      - filelock==3.20.0
      - flask==3.1.2
      - flatten-dict==0.4.2
      - flufl-lock==8.2.0
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - funcy==2.0
      - google-api-core==2.26.0
      - google-api-python-client==2.184.0
      - google-auth==2.41.1
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.2.2
      - googleapis-common-protos==1.70.0
      - gql==4.0.0
      - grandalf==0.8
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - greenlet==3.2.4
      - gto==1.9.0
      - gunicorn==23.0.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httplib2==0.31.0
      - httptools==0.7.1
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - hydra-core==1.3.2
      - idna==3.10
      - isodate==0.7.2
      - iterative-telemetry==0.0.10
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jmespath==1.0.1
      - jsonschema-path==0.3.4
      - kiwisolver==1.4.9
      - kombu==5.5.4
      - lazy-object-proxy==1.12.0
      - lxml==6.0.2
      - mako==1.3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - marshmallow==3.26.1
      - matplotlib==3.10.7
      - mcp==1.17.0
      - mdurl==0.1.2
      - mlflow==3.4.0
      - mlflow-skinny==3.4.0
      - mlflow-tracing==3.4.0
      - more-itertools==10.8.0
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - networkx==3.5
      - numpy==2.3.3
      - oauth2client==4.1.3
      - oauthlib==3.3.1
      - omegaconf==2.3.0
      - openapi-core==0.19.5
      - openapi-pydantic==0.5.1
      - openapi-schema-validator==0.6.3
      - openapi-spec-validator==0.7.2
      - opentelemetry-api==1.37.0
      - opentelemetry-proto==1.37.0
      - opentelemetry-sdk==1.37.0
      - opentelemetry-semantic-conventions==0.58b0
      - orjson==3.11.3
      - parse==1.20.2
      - pathable==0.4.4
      - pathspec==0.12.1
      - pathvalidate==3.3.1
      - platformdirs==4.5.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==6.32.1
      - psutil==7.1.0
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydantic==2.12.0
      - pydantic-core==2.41.1
      - pydantic-settings==2.11.0
      - pydot==4.0.1
      - pydrive2==1.21.3
      - pygit2==1.18.2
      - pygments==2.19.2
      - pygtrie==2.5.0
      - pyopenssl==24.2.1
      - pyparsing==3.2.5
      - pyperclip==1.11.0
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - pyyaml==6.0.3
      - referencing==0.36.2
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rich==14.1.0
      - rich-rst==1.3.1
      - rich-toolkit==0.15.1
      - rignore==0.7.1
      - rsa==4.7.2
      - ruamel-yaml==0.18.15
      - ruamel-yaml-clib==0.2.14
      - s3fs==2025.9.0
      - s3transfer==0.14.0
      - scipy==1.16.2
      - scmrepo==3.5.2
      - semver==3.0.4
      - sentry-sdk==2.42.0
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - shtab==1.7.2
      - sniffio==1.3.1
      - sqlalchemy==2.0.44
      - sqlparse==0.5.3
      - sqltrie==0.11.2
      - sse-starlette==3.0.2
      - starlette==0.48.0
      - tabulate==0.9.0
      - tomlkit==0.13.3
      - tqdm==4.67.1
      - treelib==1.8.0
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - uritemplate==4.2.0
      - urllib3==2.5.0
      - uvicorn==0.37.0
      - uvloop==0.22.1
      - vine==5.1.0
      - voluptuous==0.15.2
      - watchfiles==1.1.1
      - wcwidth==0.2.14
      - werkzeug==3.1.1
      - wrapt==1.17.3
      - yarl==1.22.0
      - zc-lockfile==4.0
