prepare:
  test_size: 0.2
  val_size: 0.1
  random_state: 42
  target_column: "Hypertension_Tests"
  numerical_features:
    - "Age"
    - "BMI" 
    - "Systolic_BP"
    - "Diastolic_BP"
    - "Heart_Rate"
  categorical_features:
    - "Gender"
    - "Medical_History"
    - "Smoking"
    - "Sporting"

preprocessing:
  numerical:
    imputer: "median"
    scaler: "standard"
  categorical:
    imputer: "most_frequent"
    encoder: "onehot"
    handle_unknown: "ignore"

model:
  model_type: "random_forest"
  random_state: 42
  n_estimators: 100
  max_depth: 10
  learning_rate: 0.1
  min_samples_split: 2
  min_samples_leaf: 1

cv:
  n_splits: 5
  random_state: 42
  strategy: "stratified"

evaluation:
  metrics:
    - "accuracy"
    - "precision"
    - "recall" 
    - "f1"
    - "roc_auc"
  threshold: 0.5

inference:
  confidence_threshold: 0.7
  batch_size: 100